spring.datasource.url: jdbc:mysql://localhost:3306/doughtodoor-om
spring.datasource.username: root
spring.datasource.password: root
spring.jpa:
  hibernate:
    ddl-auto: update

# Drop and re-create the schema for development/testing (not recommended for production)
management.endpoints.web.exposure.include: health
