spring.datasource.url: jdbc:mysql://localhost:3306/doughtodoor-om
spring.datasource.username: root
spring.datasource.password: root
spring.jpa:
  hibernate:
    ddl-auto: update

spring:
  application:
    name: order-management
  config:
    import=optional:configserver: http://localhost:8888

server:
  port: 8088 #8080 is user-management


management.endpoints.web.exposure.include: health
