
  spring:
    application:
      name: order-management
    config:
      import:
        - optional:configserver:http://localhost:8888

  server:
    port: 8088

  management:
    endpoints:
      web:
        exposure:
          include: health

