spring.datasource.url: jdbc:mysql://localhost:3306/doughtodoor-um
spring.datasource.username: root
spring.datasource.password: root
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: update

spring:
  application:
    name: user-management



management.endpoints.web.exposure.include: health

