spring.datasource.url: jdbc:mysql://localhost:3306/doughtodoor-um
spring.datasource.username: root
spring.datasource.password: root
spring.jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: update

spring:
  application:
    name: user-management
  config:
    import=optional:configserver: http://localhost:8888


management.endpoints.web.exposure.include: health

logging:
  level:
    org.springframework.security: DEBUG

